version: '3.1'

services:

  mongo:
    image: mongo
    restart: on-failure
    env_file:
      - .env
    volumes:
      - 'mongo:/data/db'
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  go-app:
    container_name: go-app
    build:
      context: .
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    depends_on:
      - mongo
    restart: on-failure

volumes:
  mongo:
